### ISSUE TITLE
Users' galleries

### ISSUE THREAD

**Issue by rusbrain** [devix-digital-org/reps#18]
Please advise how to see them?
http://142.93.227.166/gallery/photo/6697

**Comment by Voidbragon** [comment]
http://reps.ru/galleries/7632

**Comment by rusbrain** [comment]
How to get to a particular user gallery?

**Comment by rusbrain** [comment]
Please add a link to user's profile page (below "Репутация" for example):
http://reps.ru/user/3797

**Comment by rusbrain** [comment]
Old galleries not uploaded (saved to the new website)

**Comment by rusbrain** [comment]
Also, I can't remove previously uploaded pictures:
http://reps.ru/user/3797/user-gallery/7638
