### ISSUE TITLE
Need to add the Show Spoiler function of and "Hide Spoiler" in the news editor (admin panel)

### ISSUE THREAD

**Issue by ghost** [devix-digital-org/reps#43]
Need to add the Show Spoiler function of and "Hide Spoiler" in the news editor (admin panel)
![9ее](https://user-images.githubusercontent.com/54302550/72642040-906cd180-397c-11ea-9e12-1e769b0b3db9.jpg)
![9ее22](https://user-images.githubusercontent.com/54302550/72642042-906cd180-397c-11ea-932d-688188437b14.jpg)

**Comment by rusbrain** [comment]
Technically works, but no such button in the editor:
https://ibb.co/xLJ08T0

**Comment by MiGSilver** [comment]
where the button, bleyt
