### ISSUE TITLE
Не работают ссылки твича в реплеях

### ISSUE THREAD

**Issue by mSjDreamer** [devix-digital-org/reps#56]
Перестали работать ссылки на твитч в разделе реплеев
https://ibb.co/z4vhBkx

**Comment by mSjDreamer** [comment]
Проблема не решена

**Comment by mSjDreamer** [comment]
![Screenshot_13](https://user-images.githubusercontent.com/53537786/75702336-1a77bc00-5cd7-11ea-8345-b1129c7b5679.png)
Ссылки с ютуба теперь тоже не работают

**Comment by ghost** [comment]
Youtube links do not work--
