### ISSUE TITLE
Can't vote for a replay: [object Object] error

### ISSUE THREAD

**Issue by forGGe** [devix-digital-org/reps#59]
Trying to vote for a replay at http://reps.ru/replay/15848?type=user

See screenshot:

![image](https://user-images.githubusercontent.com/5261821/76141862-a18fb000-609a-11ea-8904-09d793743272.png)

Reproducibility rate: sometimes.

**Comment by rusbrain** [comment]
Author removed. Because of this reputation cannot be added.
