### ISSUE TITLE
Layout problem in replays

### ISSUE THREAD

**Issue by rusbrain** [devix-digital-org/reps#65]
http://reps.ru/replay/16174?type=user

Replay author's Minerals and gas are the same.
And the data takes more space than available.

[Screenshot](https://ibb.co/wJv7snY)

**Comment by mSjDreamer** [comment]
https://ibb.co/N1mKXZz
Раньше, рядом с ником автора отображались иконки минералов и газа, которые были некорректного (слишком большого) размера. Позже, их видимо убрали вовсе.
