### ISSUE TITLE
Проблемы с версткой для списков

### ISSUE THREAD

**Issue by calculusbearmudriyjo** [devix-digital-org/reps#91]
В новостях, если присутствует оформление в виде списков, пункты выезжают за края отступов. Как на картинке ниже

![image](https://user-images.githubusercontent.com/5278307/107156425-47c0f580-698f-11eb-9eab-e768863af32d.png)

![image](https://user-images.githubusercontent.com/5278307/107156442-67f0b480-698f-11eb-8fc2-bedb2b1d347b.png)

**Comment by rusbrain** [comment]
https://reps.ru/news/42948

**Comment by rusbrain** [comment]
По состоянию на 2021-03-19 стало [ещё хуже](https://i.ibb.co/PzhQfxR/photo-2021-03-19-19-22-46.jpg).

**Comment by mSjDreamer** [comment]
На 2021-03-25 https://ibb.co/19QVQ3X

**Comment by rusbrain** [comment]
По состоянию на 2021-04-13 стало ЕЩЁ хуже
https://reps.ru/news/43086
