### ISSUE TITLE
При попытке поставить лайк комментарию выскакивает ошибка[object Object]

### ISSUE THREAD

**Issue by calculusbearmudriyjo** [devix-digital-org/reps#92]
Если у пользователя не верифицирована почта, то при попытке поставить лайк комментарию выскакивает ошибка вида

![image](https://user-images.githubusercontent.com/5278307/107156500-c027b680-698f-11eb-8dab-49b7b8276760.png)

При этом сервер возвращает ответ

![image](https://user-images.githubusercontent.com/5278307/107156512-cddd3c00-698f-11eb-8d06-795268d3832c.png)

**Comment by rusbrain** [comment]
Пользовтель с неверифицированным емейлом вообще не должен логиниться.

**Comment by mSjDreamer** [comment]
Проведена проверка. Итог - пользователь после регистрации сразу попадает на сайт с подтвержденной почтой и может исправно ставить лайки. После того, как пользователь разлогинится, войти вновь на сайт с не подтверждённой почтой не удастся. Исключение - через функцию "напомнить пароль"
